apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp-po3
  name: tmp-po3
spec:
  containers:
  - image: nginx:alpine
    name: tmp-po3
    resources: {}
    envFrom:
      - configMapRef:
           name: multi-pod
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
