apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    args:
    - /bin/sh
    - -c
    - sleep 3600
    envFrom:
    - configMapRef:
       name: app-config
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
