apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  securityContext:
    fsGroup: 3000
  containers:
  - image: busybox
    name: busybox
    resources: {}
    args: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:
      runAsUser: 1000
    volumeMounts:
    - name: vol
      mountPath: /data/demo
  - image: busybox
    name: busybox2
    resources: {}
    securityContext:
      runAsUser: 3000
  volumes:
  - name: vol
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
