kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv
spec:
  storageClassName: normal
  capacity:
   storage: 4Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  hostPath:
   path: /etc/foo
