apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp-pod
  name: tmp-pod
spec:
  volumes:
  - name: vol
    persistentVolumeClaim:
       claimName: mypvc
  containers:
  - image: nginx:alpine
    name: tmp-pod
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
