apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp-po
  name: tmp-po
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo "Hello World" && sleep 3600
    image: busybox
    name: tmp-po
    resources: {}
    dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
status: {}
