kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv
spec:
  storageClassName: normal
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
   storage: 10Gi
  hostPath:
   path: /etc/foo
