apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-nginx # pick a name
spec:
  # which pods should be applied the policy.
  # In our case the restriction should be applied in nginx pod
  podSelector:
    matchLabels:
      app: nginx # selector for the pods
  ingress: # allow ingress traffic
    - from:
        - podSelector: # from pods
            matchLabels: # with this label
              access: granted
