apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busybox
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busybox
    spec:
      activeDeadlineSeconds: 12
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
              image: busybox
              name: busybox
              resources: {}
          restartPolicy: OnFailure
  schedule: "* * * * *"
status: {}
