apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod4
  name: pod4
spec:
  initContainers:
    - name: init
      image: busybox
      args:
        - /bin/sh
        - -c
        - wget -O /work-dir/index.html http://neverssl.com/online
      volumeMounts:
        - name: vol
          mountPath: /work-dir
  containers:
    - image: nginx
      name: pod4
      ports:
        - containerPort: 80
      resources: {}
      volumeMounts:
        - name: vol
          mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: vol
      emptyDir: {}
status: {}
