apiVersion: v1
kind: ResourceQuota
metadata:
  name: awesome-quota
  namespace: awesome-namespace
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1024m
    limits.cpu: "4"
    limits.memory: 4096m
