apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.19.0
      # define a resources that will allocate to pods
      resources:
        requests:
          cpu: "0.5"
          memory: 512m
        limits:
          cpu: "1"
          memory: 1024m
